sudo: required

script: |
  # only (attempt to) deploy non-pull request commits
  if [[ "$TRAVIS_BRANCH" = "master" && "$TRAVIS_PULL_REQUEST" = false ]]; then
    mvn deploy -U --batch-mode
  else
    # otherwise, just run test suite
    mvn verify -U --batch-mode
  fi

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y texlive-latex-base

cache:
  directories:
    - '$HOME/.m2/repository'

jdk: oraclejdk7
